import React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import Table from "./index";
import { ITableData, ITableProps } from "../../models/ITableProps";
import ProgressBar from "../ProgressBar";
import Tag from "../Tag";
const meta = {
    title: "Table",
    component: Table,
    parameters: {
        // Optional parameter to center the component in the Canvas. More info: https://storybook.js.org/docs/configure/story-layout
        layout: "centered",
    },
    // This component will have an automatically generated Autodocs entry: https://storybook.js.org/docs/writing-docs/autodocs
    tags: ["autodocs"],
    // More on argTypes: https://storybook.js.org/docs/api/argtypes
    // argTypes: {
    //   backgroundColor: { control: 'color' },
    // },
} satisfies Meta<typeof Table>;

export default meta;
type Story = StoryObj<typeof Table>;

export const SimpleTable = (args: ITableProps) => {
    const testData: ITableData = {
        headers: [
            {
                key: "driver",
                title: "DRIVER",
                dataIndex: "driver",
                sortable: true,
            },
            {
                key: "age",
                title: "AGE",
                dataIndex: "age",
                align: "center",
            },
            {
                key: "constructor",
                title: "CONSTRUCTOR",
                dataIndex: "constructor",
            },
            {
                key: "winPercent",
                title: "WIN PERCENTAGE",
                dataIndex: "winPercent",
                sortable: true,
                customComponent: (data: number) => (
                    <ProgressBar
                        showPercentage
                        completedPercent={data}
                        bgColor={"#9249B2"}
                    />
                ),
                widthPercentage: 20,
            },
            {
                key: "championships",
                title: "CHAMPIONSHIPS",
                dataIndex: "championships",
                align: "center",
            },
            {
                key: "wins",
                title: "WINS",
                dataIndex: "wins",
                align: "center",
            },
            {
                key: "nationality",
                title: "NATIONALITY",
                dataIndex: "nationality",
                align: "left",
            },
        ],
        data: [
            {
                driver: "Sebastian Vettel",
                age: 36,
                constructor: "Ferrari, Red Bull, Toro Rosso, BMW Sauber",
                winPercent: Math.round((53 * 100) / 299),
                nationality: "Germany",
                championships: 4,
                wins: 53,
            },
            {
                driver: "Lewis Hamilton",
                age: 39,
                constructor: "Mercedes",
                winPercent: Math.round((103 * 100) / 332),
                nationality: "United Kingdom",
                championships: 7,
                wins: 103,
            },
            {
                driver: "Fernando Alonso",
                age: 42,
                constructor: "Renault, McLaren, Ferrari",
                winPercent: Math.round((32 * 100) / 323),
                nationality: "Spain",
                championships: 2,
                wins: 32,
            },
            {
                driver: "Nico Rosberg",
                age: 38,
                constructor: "Mercedes, Williams",
                winPercent: Math.round((23 * 100) / 206),
                nationality: "Germany",
                championships: 1,
                wins: 23,
            },
            {
                driver: "Kimi Räikkönen",
                age: 43,
                constructor: "Ferrari, McLaren, Sauber, Lotus",
                winPercent: Math.round((21 * 100) / 343),
                nationality: "Finland",
                championships: 1,
                wins: 21,
            },
            {
                driver: "Jenson Button",
                age: 44,
                constructor: "Brawn GP, BAR, Honda, McLaren",
                winPercent: Math.round((15 * 100) / 306),
                nationality: "United Kingdom",
                championships: 1,
                wins: 15,
            },
            {
                driver: "Max Verstappen",
                age: 25,
                constructor: "Red Bull",
                winPercent: Math.round((20 * 100) / 123),
                nationality: "Netherlands",
                championships: 0,
                wins: 20,
            },
            {
                driver: "Daniel Ricciardo",
                age: 33,
                constructor: "Red Bull, Renault",
                winPercent: Math.round((9 * 100) / 200),
                nationality: "Australia",
                championships: 0,
                wins: 9,
            },
        ],
    };
    return (
        <div style={{ width: "1000px" }}>
            <Table tableData={testData} />
        </div>
    );
};
SimpleTable.args = {};
export const TableWithNestedTable = (args: ITableProps) => {
    const testData: ITableData = {
        headers: [
            {
                key: "name",
                title: "NAME",
                dataIndex: "name",
                sortable: true,
                widthPercentage: 15,
                customComponent: (data) => <a>{data}</a>,
            },
            {
                key: "dob",
                title: "DOB",
                dataIndex: "dob",
                widthPercentage: 12,
            },
            {
                key: "memberId",
                title: "MEMBER ID",
                dataIndex: "memberId",
                sortable: true,
                widthPercentage: 13,
            },
            {
                key: "attributedProvider",
                title: "ATTRIBUTED PROVIDER",
                dataIndex: "attributedProvider",
                widthPercentage: 20,
            },
            {
                key: "measure",
                title: "MEASURE",
                dataIndex: "measure",
                widthPercentage: 25,
            },
            {
                key: "result",
                title: "RESULT",
                dataIndex: "result",
                customComponent: (data) => (
                    <Tag
                        error={data === "Not Met"}
                        success={data === "Met"}
                        text={data}
                    />
                ),
                widthPercentage: 12,
            },
            {
                key: "expandArrow",
                title: "",
                dataIndex: "expandArrow",
                widthPercentage: 3,
            },
        ],
        data: [
            {
                name: "Joseph , Ada M",
                dob: "Jan 1, 1945",
                memberId: "XY12345678",
                attributedProvider: "Reyes, Nancy, MD",
                measure:
                    "Medication Adherence - Proportion of Days Covered: Statins",
                result: "Met",
                expandContent: {
                    name: "Measure Evidence",
                    type: "table",
                    table: {
                        headers: [
                            {
                                key: "prescriber",
                                title: "PRESCRIBER",
                                dataIndex: "prescriber",
                                sortable: true,
                            },
                            {
                                key: "medication",
                                title: "MEDICATION",
                                dataIndex: "medication",
                                sortable: true,
                            },
                            {
                                key: "fillQuantity",
                                title: "FILL QUANTITY",
                                dataIndex: "fillQuantity",
                                sortable: true,
                            },
                            {
                                key: "lastFill",
                                title: "LAST FILL",
                                dataIndex: "lastFill",
                                sortable: true,
                            },
                            {
                                key: "fillPharmacy",
                                title: "FILL PHARMACY",
                                dataIndex: "fillPharmacy",
                                sortable: true,
                            },
                        ],
                        data: [
                            {
                                prescriber: "Reyes, Nancy, MD",
                                medication: "Atorvastatin Tab 80 mg",
                                fillQuantity: 36,
                                lastFill: "Aug 17, 2022",
                                fillPharmacy: "ABC Pharmacy",
                            },
                            {
                                prescriber: "Reyes, Nancy, MD",
                                medication: "Pravastatin Tab 80 mg",
                                fillQuantity: 0,
                                lastFill: "Aug 24, 2022",
                                fillPharmacy: "ABC Pharmacy",
                            },
                            {
                                prescriber: "Reyes, Nancy, MD",
                                medication: "Atorvastatin Tab 80 mg",
                                fillQuantity: 0,
                                lastFill: "Aug 6, 2022",
                                fillPharmacy: "ABC Pharmacy",
                            },
                            {
                                prescriber: "Reyes, Nancy, MD",
                                medication: "Atorvastatin Tab 80 mg",
                                fillQuantity: 7,
                                lastFill: "Aug 2, 2022",
                                fillPharmacy: "ABC Pharmacy",
                            },
                        ],
                    },
                },
            },
            {
                name: "Inez, Eliot S",
                dob: "Jan 15, 1968",
                memberId: "XY12345678",
                attributedProvider: "Reyes, Nancy, MD",
                measure:
                    "Medication Adherence - Proportion of Days Covered: Statins",
                result: "Not Met",
                expandContent: {
                    name: "Measure Evidence",
                    type: "table",
                    table: {
                        headers: [
                            {
                                key: "prescriber",
                                title: "PRESCRIBER",
                                dataIndex: "prescriber",
                                sortable: true,
                            },
                            {
                                key: "medication",
                                title: "MEDICATION",
                                dataIndex: "medication",
                                sortable: true,
                            },
                            {
                                key: "fillQuantity",
                                title: "FILL QUANTITY",
                                dataIndex: "fillQuantity",
                                sortable: true,
                            },
                            {
                                key: "lastFill",
                                title: "LAST FILL",
                                dataIndex: "lastFill",
                                sortable: true,
                            },
                            {
                                key: "fillPharmacy",
                                title: "FILL PHARMACY",
                                dataIndex: "fillPharmacy",
                                sortable: true,
                            },
                        ],
                        data: [
                            {
                                prescriber: "Reyes, Nancy, MD",
                                medication: "Pravastatin Tab 80 mg",
                                fillQuantity: 0,
                                lastFill: "Aug 24, 2022",
                                fillPharmacy: "ABC Pharmacy",
                            },
                            {
                                prescriber: "Reyes, Nancy, MD",
                                medication: "Atorvastatin Tab 80 mg",
                                fillQuantity: 0,
                                lastFill: "Aug 6, 2022",
                                fillPharmacy: "ABC Pharmacy",
                            },
                            {
                                prescriber: "Reyes, Nancy, MD",
                                medication: "Atorvastatin Tab 80 mg",
                                fillQuantity: 7,
                                lastFill: "Aug 2, 2022",
                                fillPharmacy: "ABC Pharmacy",
                            },
                        ],
                    },
                },
            },
            {
                name: "Chen Victor",
                dob: "Mar 1, 1965",
                memberId: "XY12345678",
                attributedProvider: "Reyes, Nancy, MD",
                measure:
                    "Medication Adherence - Proportion of Days Covered: Statins",
                result: "Met",
                expandContent: {
                    name: "Measure Evidence",
                    type: "table",
                    table: {
                        headers: [
                            {
                                key: "prescriber",
                                title: "PRESCRIBER",
                                dataIndex: "prescriber",
                                sortable: true,
                            },
                            {
                                key: "medication",
                                title: "MEDICATION",
                                dataIndex: "medication",
                                sortable: true,
                            },
                            {
                                key: "fillQuantity",
                                title: "FILL QUANTITY",
                                dataIndex: "fillQuantity",
                                sortable: true,
                            },
                            {
                                key: "lastFill",
                                title: "LAST FILL",
                                dataIndex: "lastFill",
                                sortable: true,
                            },
                            {
                                key: "fillPharmacy",
                                title: "FILL PHARMACY",
                                dataIndex: "fillPharmacy",
                                sortable: true,
                            },
                        ],
                        data: [
                            {
                                prescriber: "Reyes, Nancy, MD",
                                medication: "Atorvastatin Tab 80 mg",
                                fillQuantity: 7,
                                lastFill: "Aug 2, 2022",
                                fillPharmacy: "ABC Pharmacy",
                            },
                        ],
                    },
                },
            },
        ],
    };
    return (
        <div style={{ width: "900px" }}>
            <Table tableData={testData} />
        </div>
    );
};
TableWithNestedTable.args = {};
export const SimpleTableWithPagination = (args: ITableProps) => {
    const testData: ITableData = {
        headers: [
            {
                key: "driver",
                title: "DRIVER",
                dataIndex: "driver",
                sortable: true,
                widthPercentage: 20,
            },
            {
                key: "age",
                title: "AGE",
                dataIndex: "age",
                align: "center",
                widthPercentage: 5,
            },
            {
                key: "constructor",
                title: "CONSTRUCTOR",
                dataIndex: "constructor",
                widthPercentage: 30,
            },
            {
                key: "winPercent",
                title: "WIN PERCENTAGE",
                dataIndex: "winPercent",
                sortable: true,
                customComponent: (data: number) => (
                    <ProgressBar
                        showPercentage
                        completedPercent={data}
                        bgColor={"#9249B2"}
                    />
                ),
                widthPercentage: 20,
            },
            {
                key: "championships",
                title: "Titles",
                dataIndex: "championships",
                align: "center",
            },
            {
                key: "wins",
                title: "WINS",
                dataIndex: "wins",
                align: "center",
                widthPercentage: 5,
            },
            {
                key: "nationality",
                title: "NATIONALITY",
                dataIndex: "nationality",
                align: "left",
                widthPercentage: 15,
            },
        ],
        data: [
            {
                driver: "Sebastian Vettel",
                age: 36,
                constructor: "Ferrari, Red Bull, Toro Rosso, BMW Sauber",
                winPercent: Math.round((53 * 100) / 299),
                nationality: "Germany",
                championships: 4,
                wins: 53,
            },
            {
                driver: "Lewis Hamilton",
                age: 39,
                constructor: "Mercedes",
                winPercent: Math.round((103 * 100) / 332),
                nationality: "United Kingdom",
                championships: 7,
                wins: 103,
            },
            {
                driver: "Fernando Alonso",
                age: 42,
                constructor: "Renault, McLaren, Ferrari",
                winPercent: Math.round((32 * 100) / 323),
                nationality: "Spain",
                championships: 2,
                wins: 32,
            },
            {
                driver: "Nico Rosberg",
                age: 38,
                constructor: "Mercedes, Williams",
                winPercent: Math.round((23 * 100) / 206),
                nationality: "Germany",
                championships: 1,
                wins: 23,
            },
            {
                driver: "Kimi Räikkönen",
                age: 43,
                constructor: "Ferrari, McLaren, Sauber, Lotus",
                winPercent: Math.round((21 * 100) / 343),
                nationality: "Finland",
                championships: 1,
                wins: 21,
            },
            {
                driver: "Jenson Button",
                age: 44,
                constructor: "Brawn GP, BAR, Honda, McLaren",
                winPercent: Math.round((15 * 100) / 306),
                nationality: "United Kingdom",
                championships: 1,
                wins: 15,
            },
            {
                driver: "Max Verstappen",
                age: 25,
                constructor: "Red Bull",
                winPercent: Math.round((20 * 100) / 123),
                nationality: "Netherlands",
                championships: 0,
                wins: 20,
            },
            {
                driver: "Daniel Ricciardo",
                age: 33,
                constructor: "Red Bull, Renault",
                winPercent: Math.round((9 * 100) / 200),
                nationality: "Australia",
                championships: 0,
                wins: 9,
            },
            {
                driver: "Michael Schumacher",
                age: 55,
                constructor: "Ferrari, Benetton, Mercedes",
                winPercent: Math.round((91 * 100) / 306),
                nationality: "Germany",
                championships: 7,
                wins: 91,
            },
            {
                driver: "Ayrton Senna",
                age: 34,
                constructor: "McLaren, Lotus, Williams",
                winPercent: Math.round((41 * 100) / 162),
                nationality: "Brazil",
                championships: 3,
                wins: 41,
            },
            {
                driver: "Alain Prost",
                age: 68,
                constructor: "McLaren, Ferrari, Williams, Renault",
                winPercent: Math.round((51 * 100) / 202),
                nationality: "France",
                championships: 4,
                wins: 51,
            },
            {
                driver: "Nelson Piquet",
                age: 71,
                constructor: "Brabham, Williams, Benetton",
                winPercent: Math.round((23 * 100) / 204),
                nationality: "Brazil",
                championships: 3,
                wins: 23,
            },
            {
                driver: "Jackie Stewart",
                age: 83,
                constructor: "Tyrrell, Matra, BRM",
                winPercent: Math.round((27 * 100) / 100),
                nationality: "United Kingdom",
                championships: 3,
                wins: 27,
            },
            {
                driver: "Jim Clark",
                age: 87,
                constructor: "Lotus",
                winPercent: Math.round((25 * 100) / 72),
                nationality: "United Kingdom",
                championships: 2,
                wins: 25,
            },
            {
                driver: "Niki Lauda",
                age: 71,
                constructor: "Ferrari, McLaren",
                winPercent: Math.round((25 * 100) / 171),
                nationality: "Austria",
                championships: 3,
                wins: 25,
            },
            {
                driver: "Emerson Fittipaldi",
                age: 75,
                constructor: "Lotus, McLaren, Fittipaldi",
                winPercent: Math.round((14 * 100) / 144),
                nationality: "Brazil",
                championships: 2,
                wins: 14,
            },
            {
                driver: "Graham Hill",
                age: 92,
                constructor: "BRM, Lotus",
                winPercent: Math.round((14 * 100) / 176),
                nationality: "United Kingdom",
                championships: 2,
                wins: 14,
            },
            {
                driver: "Mika Häkkinen",
                age: 54,
                constructor: "McLaren",
                winPercent: Math.round((20 * 100) / 161),
                nationality: "Finland",
                championships: 2,
                wins: 20,
            },
            {
                driver: "Alberto Ascari",
                age: 108,
                constructor: "Ferrari, Maserati",
                winPercent: Math.round((13 * 100) / 32),
                nationality: "Italy",
                championships: 2,
                wins: 13,
            },
            {
                driver: "Fernando Alonso",
                age: 42,
                constructor: "Renault, McLaren, Ferrari",
                winPercent: Math.round((32 * 100) / 323),
                nationality: "Spain",
                championships: 2,
                wins: 32,
            },
            {
                driver: "Gilles Villeneuve",
                age: 32,
                constructor: "Ferrari",
                winPercent: Math.round((6 * 100) / 67),
                nationality: "Canada",
                championships: 0,
                wins: 6,
            },
            {
                driver: "Juan Manuel Fangio",
                age: 84,
                constructor: "Alfa Romeo, Maserati, Mercedes, Ferrari",
                winPercent: Math.round((24 * 100) / 51),
                nationality: "Argentina",
                championships: 5,
                wins: 24,
            },
            {
                driver: "Stirling Moss",
                age: 92,
                constructor: "Mercedes, Maserati, Vanwall, Cooper",
                winPercent: Math.round((16 * 100) / 66),
                nationality: "United Kingdom",
                championships: 0,
                wins: 16,
            },
            {
                driver: "Damon Hill",
                age: 63,
                constructor: "Williams",
                winPercent: Math.round((22 * 100) / 115),
                nationality: "United Kingdom",
                championships: 1,
                wins: 22,
            },
            {
                driver: "Keke Rosberg",
                age: 74,
                constructor: "Williams",
                winPercent: Math.round((5 * 100) / 128),
                nationality: "Finland",
                championships: 1,
                wins: 5,
            },
            {
                driver: "Mike Hawthorn",
                age: 74,
                constructor: "Ferrari",
                winPercent: Math.round((3 * 100) / 47),
                nationality: "United Kingdom",
                championships: 1,
                wins: 3,
            },
            {
                driver: "Jochen Rindt",
                age: 28,
                constructor: "Lotus",
                winPercent: Math.round((6 * 100) / 60),
                nationality: "Austria",
                championships: 1,
                wins: 6,
            },
            {
                driver: "Phil Hill",
                age: 93,
                constructor: "Ferrari, Cooper",
                winPercent: Math.round((3 * 100) / 48),
                nationality: "United States",
                championships: 1,
                wins: 3,
            },
            {
                driver: "John Surtees",
                age: 87,
                constructor: "Ferrari, Cooper, Honda",
                winPercent: Math.round((6 * 100) / 112),
                nationality: "United Kingdom",
                championships: 1,
                wins: 6,
            },
            {
                driver: "Jacques Villeneuve",
                age: 50,
                constructor: "Williams, BAR",
                winPercent: Math.round((11 * 100) / 163),
                nationality: "Canada",
                championships: 1,
                wins: 11,
            },
            {
                driver: "Denny Hulme",
                age: 84,
                constructor: "Brabham, McLaren",
                winPercent: Math.round((8 * 100) / 112),
                nationality: "New Zealand",
                championships: 1,
                wins: 8,
            },
            {
                driver: "Mario Andretti",
                age: 82,
                constructor: "Lotus, Ferrari",
                winPercent: Math.round((12 * 100) / 128),
                nationality: "United States",
                championships: 1,
                wins: 12,
            },
            {
                driver: "Nico Rosberg",
                age: 38,
                constructor: "Mercedes, Williams",
                winPercent: Math.round((23 * 100) / 206),
                nationality: "Germany",
                championships: 1,
                wins: 23,
            },
            {
                driver: "Jody Scheckter",
                age: 72,
                constructor: "Ferrari, Tyrrell, Wolf",
                winPercent: Math.round((10 * 100) / 113),
                nationality: "South Africa",
                championships: 1,
                wins: 10,
            },
            {
                driver: "James Hunt",
                age: 45,
                constructor: "McLaren",
                winPercent: Math.round((10 * 100) / 92),
                nationality: "United Kingdom",
                championships: 1,
                wins: 10,
            },
            {
                driver: "Kimi Räikkönen",
                age: 43,
                constructor: "Ferrari, McLaren, Sauber, Lotus",
                winPercent: Math.round((21 * 100) / 343),
                nationality: "Finland",
                championships: 1,
                wins: 21,
            },
            {
                driver: "Jack Brabham",
                age: 88,
                constructor: "Brabham, Cooper",
                winPercent: Math.round((14 * 100) / 126),
                nationality: "Australia",
                championships: 3,
                wins: 14,
            },
            {
                driver: "Alan Jones",
                age: 76,
                constructor: "Williams",
                winPercent: Math.round((12 * 100) / 116),
                nationality: "Australia",
                championships: 1,
                wins: 12,
            },
            {
                driver: "Giacomo Agostini",
                age: 79,
                constructor: "Ferrari, Williams",
                winPercent: Math.round((3 * 100) / 26),
                nationality: "Italy",
                championships: 0,
                wins: 3,
            },
            {
                driver: "Tony Brooks",
                age: 90,
                constructor: "Ferrari, Vanwall, BRM",
                winPercent: Math.round((6 * 100) / 38),
                nationality: "United Kingdom",
                championships: 0,
                wins: 6,
            },
            {
                driver: "Stefan Bellof",
                age: 36,
                constructor: "Tyrrell",
                winPercent: Math.round((0 * 100) / 20),
                nationality: "Germany",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Riccardo Patrese",
                age: 68,
                constructor: "Brabham, Williams",
                winPercent: Math.round((6 * 100) / 256),
                nationality: "Italy",
                championships: 0,
                wins: 6,
            },
            {
                driver: "Carlos Reutemann",
                age: 79,
                constructor: "Williams, Ferrari, Brabham",
                winPercent: Math.round((12 * 100) / 146),
                nationality: "Argentina",
                championships: 0,
                wins: 12,
            },
            {
                driver: "Mark Webber",
                age: 47,
                constructor: "Red Bull",
                winPercent: Math.round((9 * 100) / 215),
                nationality: "Australia",
                championships: 0,
                wins: 9,
            },
            {
                driver: "Felipe Massa",
                age: 42,
                constructor: "Ferrari, Williams",
                winPercent: Math.round((11 * 100) / 269),
                nationality: "Brazil",
                championships: 0,
                wins: 11,
            },
            {
                driver: "Didier Pironi",
                age: 35,
                constructor: "Ferrari, Ligier",
                winPercent: Math.round((3 * 100) / 72),
                nationality: "France",
                championships: 0,
                wins: 3,
            },
            {
                driver: "Ralf Schumacher",
                age: 47,
                constructor: "Williams, Toyota",
                winPercent: Math.round((6 * 100) / 181),
                nationality: "Germany",
                championships: 0,
                wins: 6,
            },
            {
                driver: "Vitaly Petrov",
                age: 38,
                constructor: "Renault",
                winPercent: Math.round((0 * 100) / 57),
                nationality: "Russia",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Jean Alesi",
                age: 58,
                constructor: "Ferrari, Tyrrell, Benetton",
                winPercent: Math.round((1 * 100) / 202),
                nationality: "France",
                championships: 0,
                wins: 1,
            },
            {
                driver: "Rubens Barrichello",
                age: 50,
                constructor: "Ferrari, Brawn GP, Jordan",
                winPercent: Math.round((11 * 100) / 322),
                nationality: "Brazil",
                championships: 0,
                wins: 11,
            },
            {
                driver: "Carlos Sainz Jr.",
                age: 28,
                constructor: "McLaren, Toro Rosso",
                winPercent: Math.round((0 * 100) / 122),
                nationality: "Spain",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Romain Grosjean",
                age: 37,
                constructor: "Lotus, Haas",
                winPercent: Math.round((0 * 100) / 179),
                nationality: "France",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Jules Bianchi",
                age: 25,
                constructor: "Marussia",
                winPercent: Math.round((0 * 100) / 34),
                nationality: "France",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Esteban Ocon",
                age: 26,
                constructor: "Renault, Force India",
                winPercent: Math.round((0 * 100) / 75),
                nationality: "France",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Sergio Perez",
                age: 33,
                constructor: "Force India, Racing Point",
                winPercent: Math.round((1 * 100) / 212),
                nationality: "Mexico",
                championships: 0,
                wins: 1,
            },
            {
                driver: "Pierre Gasly",
                age: 26,
                constructor: "AlphaTauri",
                winPercent: Math.round((1 * 100) / 85),
                nationality: "France",
                championships: 0,
                wins: 1,
            },
            {
                driver: "Lando Norris",
                age: 23,
                constructor: "McLaren",
                winPercent: Math.round((0 * 100) / 63),
                nationality: "United Kingdom",
                championships: 0,
                wins: 0,
            },
            {
                driver: "George Russell",
                age: 25,
                constructor: "Williams",
                winPercent: Math.round((0 * 100) / 48),
                nationality: "United Kingdom",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Nicholas Latifi",
                age: 26,
                constructor: "Williams",
                winPercent: Math.round((0 * 100) / 40),
                nationality: "Canada",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Antonio Giovinazzi",
                age: 28,
                constructor: "Alfa Romeo",
                winPercent: Math.round((0 * 100) / 43),
                nationality: "Italy",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Mick Schumacher",
                age: 24,
                constructor: "Haas",
                winPercent: Math.round((0 * 100) / 21),
                nationality: "Germany",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Nikita Mazepin",
                age: 23,
                constructor: "Haas",
                winPercent: Math.round((0 * 100) / 24),
                nationality: "Russia",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Callum Ilott",
                age: 23,
                constructor: "Alfa Romeo",
                winPercent: Math.round((0 * 100) / 2),
                nationality: "United Kingdom",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Nigel Mansell",
                age: 69,
                constructor: "Williams, Ferrari",
                winPercent: Math.round((31 * 100) / 187),
                nationality: "United Kingdom",
                championships: 1,
                wins: 31,
            },
            {
                driver: "Jochen Mass",
                age: 75,
                constructor: "McLaren, March",
                winPercent: Math.round((1 * 100) / 114),
                nationality: "Germany",
                championships: 0,
                wins: 1,
            },
            {
                driver: "Eddie Irvine",
                age: 58,
                constructor: "Ferrari, Jordan",
                winPercent: Math.round((4 * 100) / 148),
                nationality: "United Kingdom",
                championships: 0,
                wins: 4,
            },
            {
                driver: "Giancarlo Fisichella",
                age: 49,
                constructor: "Renault, Force India",
                winPercent: Math.round((3 * 100) / 231),
                nationality: "Italy",
                championships: 0,
                wins: 3,
            },
            {
                driver: "Johnny Herbert",
                age: 58,
                constructor: "Benetton, Sauber",
                winPercent: Math.round((3 * 100) / 161),
                nationality: "United Kingdom",
                championships: 0,
                wins: 3,
            },
            {
                driver: "Ricardo Patrese",
                age: 68,
                constructor: "Brabham, Williams",
                winPercent: Math.round((6 * 100) / 256),
                nationality: "Italy",
                championships: 0,
                wins: 6,
            },
            {
                driver: "Gerhard Berger",
                age: 63,
                constructor: "Ferrari, McLaren",
                winPercent: Math.round((10 * 100) / 210),
                nationality: "Austria",
                championships: 0,
                wins: 10,
            },
            {
                driver: "Thierry Boutsen",
                age: 66,
                constructor: "Williams, Benetton",
                winPercent: Math.round((3 * 100) / 163),
                nationality: "Belgium",
                championships: 0,
                wins: 3,
            },
            {
                driver: "Pedro de la Rosa",
                age: 52,
                constructor: "Arrows, Jaguar",
                winPercent: Math.round((0 * 100) / 105),
                nationality: "Spain",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Maurice Trintignant",
                age: 87,
                constructor: "Ferrari, Gordini",
                winPercent: Math.round((2 * 100) / 82),
                nationality: "France",
                championships: 0,
                wins: 2,
            },
            {
                driver: "Jo Siffert",
                age: 84,
                constructor: "Lotus, Brabham, Rob Walker Racing Team",
                winPercent: Math.round((2 * 100) / 96),
                nationality: "Switzerland",
                championships: 0,
                wins: 2,
            },
            {
                driver: "Clay Regazzoni",
                age: 82,
                constructor: "Ferrari, BRM, Shadow",
                winPercent: Math.round((5 * 100) / 132),
                nationality: "Switzerland",
                championships: 0,
                wins: 5,
            },
            {
                driver: "Luigi Musso",
                age: 95,
                constructor: "Ferrari, Maserati",
                winPercent: Math.round((1 * 100) / 24),
                nationality: "Italy",
                championships: 0,
                wins: 1,
            },
            {
                driver: "Peter Revson",
                age: 35,
                constructor: "McLaren, Shadow",
                winPercent: Math.round((2 * 100) / 31),
                nationality: "United States",
                championships: 0,
                wins: 2,
            },
            {
                driver: "Carlos Pace",
                age: 75,
                constructor: "Brabham, Surtees",
                winPercent: Math.round((1 * 100) / 72),
                nationality: "Brazil",
                championships: 0,
                wins: 1,
            },
            {
                driver: "John Watson",
                age: 76,
                constructor: "McLaren, Brabham",
                winPercent: Math.round((5 * 100) / 152),
                nationality: "United Kingdom",
                championships: 0,
                wins: 5,
            },
            {
                driver: "Jean-Pierre Jarier",
                age: 76,
                constructor: "Shadow, Tyrrell",
                winPercent: Math.round((0 * 100) / 143),
                nationality: "France",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Vittorio Brambilla",
                age: 84,
                constructor: "March, Surtees, Alfa Romeo",
                winPercent: Math.round((1 * 100) / 79),
                nationality: "Italy",
                championships: 0,
                wins: 1,
            },
            {
                driver: "Carlos Pace",
                age: 75,
                constructor: "Brabham, Surtees",
                winPercent: Math.round((1 * 100) / 72),
                nationality: "Brazil",
                championships: 0,
                wins: 1,
            },
            {
                driver: "Carlos Reutemann",
                age: 79,
                constructor: "Williams, Ferrari, Brabham",
                winPercent: Math.round((12 * 100) / 146),
                nationality: "Argentina",
                championships: 0,
                wins: 12,
            },
            {
                driver: "Alan Jones",
                age: 76,
                constructor: "Williams",
                winPercent: Math.round((12 * 100) / 116),
                nationality: "Australia",
                championships: 1,
                wins: 12,
            },
            {
                driver: "Giacomo Agostini",
                age: 79,
                constructor: "Ferrari, Williams",
                winPercent: Math.round((3 * 100) / 26),
                nationality: "Italy",
                championships: 0,
                wins: 3,
            },
            {
                driver: "Tony Brooks",
                age: 90,
                constructor: "Ferrari, Vanwall, BRM",
                winPercent: Math.round((6 * 100) / 38),
                nationality: "United Kingdom",
                championships: 0,
                wins: 6,
            },
            {
                driver: "Stefan Bellof",
                age: 36,
                constructor: "Tyrrell",
                winPercent: Math.round((0 * 100) / 20),
                nationality: "Germany",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Riccardo Patrese",
                age: 68,
                constructor: "Brabham, Williams",
                winPercent: Math.round((6 * 100) / 256),
                nationality: "Italy",
                championships: 0,
                wins: 6,
            },
            {
                driver: "Carlos Reutemann",
                age: 79,
                constructor: "Williams, Ferrari, Brabham",
                winPercent: Math.round((12 * 100) / 146),
                nationality: "Argentina",
                championships: 0,
                wins: 12,
            },
            {
                driver: "Mark Webber",
                age: 47,
                constructor: "Red Bull",
                winPercent: Math.round((9 * 100) / 215),
                nationality: "Australia",
                championships: 0,
                wins: 9,
            },
            {
                driver: "Felipe Massa",
                age: 42,
                constructor: "Ferrari, Williams",
                winPercent: Math.round((11 * 100) / 269),
                nationality: "Brazil",
                championships: 0,
                wins: 11,
            },
            {
                driver: "Didier Pironi",
                age: 35,
                constructor: "Ferrari, Ligier",
                winPercent: Math.round((3 * 100) / 72),
                nationality: "France",
                championships: 0,
                wins: 3,
            },
            {
                driver: "Ralf Schumacher",
                age: 47,
                constructor: "Williams, Toyota",
                winPercent: Math.round((6 * 100) / 181),
                nationality: "Germany",
                championships: 0,
                wins: 6,
            },
            {
                driver: "Vitaly Petrov",
                age: 38,
                constructor: "Renault",
                winPercent: Math.round((0 * 100) / 57),
                nationality: "Russia",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Jean Alesi",
                age: 58,
                constructor: "Ferrari, Tyrrell, Benetton",
                winPercent: Math.round((1 * 100) / 202),
                nationality: "France",
                championships: 0,
                wins: 1,
            },
            {
                driver: "Rubens Barrichello",
                age: 50,
                constructor: "Ferrari, Brawn GP, Jordan",
                winPercent: Math.round((11 * 100) / 322),
                nationality: "Brazil",
                championships: 0,
                wins: 11,
            },
            {
                driver: "Carlos Sainz Jr.",
                age: 28,
                constructor: "McLaren, Toro Rosso",
                winPercent: Math.round((0 * 100) / 122),
                nationality: "Spain",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Romain Grosjean",
                age: 37,
                constructor: "Lotus, Haas",
                winPercent: Math.round((0 * 100) / 179),
                nationality: "France",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Jules Bianchi",
                age: 25,
                constructor: "Marussia",
                winPercent: Math.round((0 * 100) / 34),
                nationality: "France",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Esteban Ocon",
                age: 26,
                constructor: "Renault, Force India",
                winPercent: Math.round((0 * 100) / 75),
                nationality: "France",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Sergio Perez",
                age: 33,
                constructor: "Force India, Racing Point",
                winPercent: Math.round((1 * 100) / 212),
                nationality: "Mexico",
                championships: 0,
                wins: 1,
            },
            {
                driver: "Pierre Gasly",
                age: 26,
                constructor: "AlphaTauri",
                winPercent: Math.round((1 * 100) / 85),
                nationality: "France",
                championships: 0,
                wins: 1,
            },
            {
                driver: "Lando Norris",
                age: 23,
                constructor: "McLaren",
                winPercent: Math.round((0 * 100) / 63),
                nationality: "United Kingdom",
                championships: 0,
                wins: 0,
            },
            {
                driver: "George Russell",
                age: 25,
                constructor: "Williams",
                winPercent: Math.round((0 * 100) / 48),
                nationality: "United Kingdom",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Nicholas Latifi",
                age: 26,
                constructor: "Williams",
                winPercent: Math.round((0 * 100) / 40),
                nationality: "Canada",
                championships: 0,
                wins: 0,
            },
            {
                driver: "Antonio Giovinazzi",
                age: 28,
                constructor: "Alfa Romeo",
                winPercent: Math.round((0 * 100) / 43),
                nationality: "Italy",
                championships: 0,
                wins: 0,
            },
        ],
    };
    return (
        <div style={{ width: "1000px" }}>
            <Table tableData={testData} />
        </div>
    );
};
SimpleTableWithPagination.args = {};
